POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "sharon_carlow",
  "password": "sharonpassword123"
}

####
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "sharon_carlow",
  "password": "sharonpassword123"
}