### Get all persons
GET http://localhost:3001/api/persons

###

### Get info page
GET http://localhost:3001/info

###

### Delete a person (Replace ID with a real one from your GET list!)
DELETE http://localhost:3001/api/persons/69c2961525239efdf105ab34

###

### Create a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Limerick Larry",
    "number": "061-123456"
}

###

### Update a person (Replace ID with Sandra's or Tommy's ID)
PUT http://localhost:3001/api/persons/69c28c0c94db4841fcee6fba
Content-Type: application/json

{
    "name": "Sandra Pretty",
    "number": "085-999-888"
}